# Generated by Django 2.1 on 2019-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=10)),
                ('classinfo', models.CharField(max_length=10)),
                ('mothername', models.CharField(max_length=30)),
                ('fathername', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('dob', models.DateField(auto_now_add=True)),
                ('mobileno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
    ]
